kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: condaforge/linux-anvil-aarch64
  privileged: true
  commands:
  - ls /
  - ls /opt
  - . /opt/conda/etc/profile.d/conda.sh
  - conda info
  - whoami
