kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: test
  image: condaforge/linux-anvil-aarch64
  priviledged: true
  commands:
  - /opt/conda/bin/tini -- /opt/docker/bin/entrypoint /bin/bash
  - conda info
  - whoami
