kind: pipeline
name: amd

platform:
  os: linux
  arch: amd64

steps:
- name: build
  image: gcc
  commands:
  - lscpu
  - uname -a
  - free -m

---
kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: gcc
  commands:
  - lscpu
  - uname -a
  - free -m

---
kind: pipeline
name: arm

platform:
  os: linux
  arch: arm

steps:
- name: build
  image: gcc
  commands:
  - lscpu
  - uname -a
  - free -m
