kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: docker
  commands:
    - docker info
    - docker run condaforge/linux-anvil-aarch64 whoami
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
