kind: pipeline
name: arm64

platform:
  os: linux
  arch: arm64

steps:
- name: build
  image: ubuntu-16.04
  commands:
  - lscpu
  - uname -a
  - free -m
  - docker info
  - docker run condaforge/linux-anvil-aarch64 whoami
